"""empty message

Revision ID: 8a53efb03017
Revises: 3afd33e11129
Create Date: 2023-12-10 10:22:22.589540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a53efb03017'
down_revision = '3afd33e11129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        # Name the foreign key constraint
        batch_op.create_foreign_key('fk_event_creator_id', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
